LAVADIR		= ../src
IPCOREDIR	= ipcore_dir

MAIN		= Input
TOP		= Input
VHDL_MODS	=
XAW_MODS	= dcm_32_to_50p35
HS_MODS		= Utils DCM Video

GHC_FLAGS	= -Werror -fwarn-unused-imports -fwarn-unused-matches -fwarn-unused-binds

include Make.vars
include Make.rules
